<?php

namespace Database\Seeders;

use App\Domain\Users\Entities\UserProfile;
use App\Infrastructure\Authorization\PermissionRegistrar;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        PermissionRegistrar::sync();
        $name = 'John Doe';
        $avatarUrl = 'https://api.dicebear.com/9.x/shapes/svg?seed=' . urlencode($name);

        // 1. Create the specific "John Doe" user
        $user = User::factory()->create([
            'name' => $name,
            'email' => 'john.doe@example.com',
            'password' => Hash::make('password'), // Manually hashing for clarity
            'email_verified_at' => now(),         // Mark email as verified
            'is_password_set' => true,
        ]);

        $user->assignRole('instructor');

        // 2. Create an empty Profile for him
        UserProfile::create([
            'user_id' => $user->id,
            'bio' => 'I am a test user generated by the seeder.',
            'avatar_url' => $avatarUrl,
            'marketing_opt_in' => true,
            'locale' => 'en',
            'timezone' => 'Asia/Dhaka',
        ]);
    }
}
